os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - 10
  - 12
  - "node"
before_script:
  - git config --global user.name "webpro"
  - git config --global user.email "lars@webpro.nl"
cache:
  npm: false
matrix:
  exclude:
    - os: windows
      node_js: 10
    - os: linux
      node_js: 12
  include:
    - os: linux
      node_js: 12
      script: npm run codecov
